config/routes.rb
Fts4::Application.routes.draw do

  root  "static_pages#home"

  match "/signup",  to: "users#new",            via: "get"
  match "/help",    to: "static_pages#help",    via: "get"
  match "/about",   to: "static_pages#about",   via: "get"
  match "/signin", to: "sessions#new", via: "get"
  match "/signout", to: "sessions#destroy", via: :delete
  match "/home", to: "static_pages#home", via: :get

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :examinations, only: [:index, :show] do
    resources :answer_sheets
  end

  namespace :admin do
    root to: "static_pages#home"
    match "/help",    to: "static_pages#help",    via: :get
    match "/about",   to: "static_pages#about",   via: :get
    match "/signin",  to: "sessions#new",         via: :get
    match "/signout", to: "sessions#destroy",     via: :delete
    match "/home",    to: "static_pages#home",    via: :get
    resources :sessions
    resources :admins
    resources :users
    resources :subjects
    resources :questions
    resources :examinations
  end

end

app/models/subject.rb
class Subject < ActiveRecord::Base
  has_many :examinations, dependent: :destroy
  has_many :questions, dependent: :destroy
end

app/controllers/admin/subjects_controller.rb
class Admin::SubjectsController < Admin::ApplicationController
  before_action :load_object, only: [:show, :edit, :update, :destroy]

  def index
    @subjects = Subject.all.paginate page: params[:page], per_page: 15
  end

  def show
  end

  def new
    @subject = Subject.new
  end

  def edit
  end

  def create
    subject = Subject.new subject_params
    if subject.save
      flash[:success] = "Create #{subject.name} finished!"
    else
      flash[:error] = "Can't save"
    end
    redirect_to admin_subjects_url
  end

  def update
    if @subject.update_attributes subject_params
      flash[:success] = "Update #{@subject.name} finished!"
    else
      flash[:error] = "Update failed!"
    end
    redirect_to admin_subjects_url
  end

  def destroy
    @subject.destroy
    flash[:success] = "Subject: #{@subject.name} destroyed."
    redirect_to admin_subjects_url
  end

  private

    def load_object
      @subject = Subject.find params[:id]
    end

    def subject_params
      params.require(:subject).permit(:name)
    end
end

app/views/admin/subjects/_form.html.erb
<%= form_for [:admin, @subject] do |f| %>
  <%= f.label :name %><br />
  <%= f.text_field :name %>
  <p><%= f.submit "Submit", class: "btn btn-large btn-primary" %></p>
<% end %>

app/views/admin/subjects/_subject.html.erb
<li>
  Subject: <%= link_to subject.name, admin_subject_path(subject) %>,
    <%= link_to "edit", edit_admin_subject_path(subject)%>
    | <%= link_to "delete", admin_subject_path(subject), method: :delete,
        data: { confirm: "You sure?" } %>
</li>

app/views/admin/subjects/edit.html.erb
<h1>Edit subject</h1>
<div class="row"%>
  <div class="span6 offset3">
    <%= render 'form' %>
  </div>
</div>

app/views/admin/subjects/index.html.erb
<% provide(:title, "List subjects") %>
<h1>List subjects</h1>
<h2><%= link_to "Create new subject", new_admin_subject_path %> </h2>
<%= will_paginate %>
  <ul class="subjects">
    <%= render @subjects %>
  </ul>
<%= will_paginate %>

app/views/admin/subjects/new.html.erb
<h1>Create subject</h1>
<div class="row"%>
  <div class="span6 offset3">
    <%= render 'form' %>
  </div>
</div>

app/views/admin/subjects/show.html.erb
<h1><%= @subject.name %></h1>