config/routes.rb
Fts4::Application.routes.draw do

  root  "static_pages#home"

  match "/signup",  to: "users#new",            via: "get"
  match "/help",    to: "static_pages#help",    via: "get"
  match "/about",   to: "static_pages#about",   via: "get"
  match "/signin", to: "sessions#new", via: "get"
  match "/signout", to: "sessions#destroy", via: :delete
  match "/home", to: "static_pages#home", via: :get

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :examinations, only: [:index, :show] do
    resources :answer_sheets
  end

  namespace :admin do
    root to: "static_pages#home"
    match "/help",    to: "static_pages#help",    via: :get
    match "/about",   to: "static_pages#about",   via: :get
    match "/signin",  to: "sessions#new",         via: :get
    match "/signout", to: "sessions#destroy",     via: :delete
    match "/home",    to: "static_pages#home",    via: :get
    resources :sessions
    resources :admins
    resources :users
    resources :subjects
    resources :questions
    resources :examinations
  end

end

app/views/layouts/admin/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by NNT
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/admin/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "test app", "#", id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", "/admin/home" %></li>
          <li><%= link_to "Help", "/admin/help" %></li>
          <li><%= link_to "Examinations", admin_examinations_path %></li>
          <li><%= link_to "Subjects", admin_subjects_path %></li>
          <li><%= link_to "Questions", admin_questions_path %></li>
          <li><%= link_to "Users", admin_users_path %></li>
          <li><%= link_to "Admins", admin_admins_path %></li>
          <% if admin_signed_in? %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", admin_admin_url(current_admin) %></li>
                <li><%= link_to "Settings", edit_admin_admin_url(current_admin) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", admin_signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", "/admin/signin" %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/admin/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fts4</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/admin/header' %>
  <div class="container">
    <%flash.each do |key, value| %>
      <div class="alert alert-<%= key%>"><%= value%></div>
    <%end%>
    <%= yield %>
  </div>
  <div>    
    <%= render 'layouts/admin/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>