config/routes.rb
Fts4::Application.routes.draw do

  root  "static_pages#home"

  match "/signup",  to: "users#new",            via: "get"
  match "/help",    to: "static_pages#help",    via: "get"
  match "/about",   to: "static_pages#about",   via: "get"
  match "/signin", to: "sessions#new", via: "get"
  match "/signout", to: "sessions#destroy", via: :delete
  match "/home", to: "static_pages#home", via: :get

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :examinations, only: [:index, :show] do
    resources :answer_sheets
  end

  namespace :admin do
    root to: "static_pages#home"
    match "/help",    to: "static_pages#help",    via: :get
    match "/about",   to: "static_pages#about",   via: :get
    match "/signin",  to: "sessions#new",         via: :get
    match "/signout", to: "sessions#destroy",     via: :delete
    match "/home",    to: "static_pages#home",    via: :get
    resources :sessions
    resources :admins
    resources :users
    resources :subjects
    resources :questions
    resources :examinations
  end

end

app/views/admin/admins/_admin.html.erb
<li>
  <%= gravatar_for admin %>
  Name: <%= link_to admin.name, admin_admin_path(admin) %>,
    <%= link_to "edit", edit_admin_admin_path(admin)%>
    <% unless current_admin? admin %>
      | <%= link_to "delete", admin_admin_path(admin), method: :delete,
        data: { confirm: "You sure?" } %>
    <% end %>
</li>

app/views/admin/admins/edit.html.erb
<% provide(:title, "Edit admin") %>
<h1> Update your profile </h1>
<div class="row">
  <div class="span6 offset3">
  <%= form_for [:admin, @admin] do |f| %>
    <% @object = @admin %>
    <%= render 'shared/error_messages' %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :email %>
    <%= f.text_field :email %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation, "Confirm Password" %>
    <%= f.password_field :password_confirmation %>

    <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
  <% end %>
  <%= gravatar_for @admin %>
  <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/admin/admins/index.html.erb
<% provide(:title, "List admins") %>
<h1>List Admins</h1>
<h2><%= link_to "Create new admin", new_admin_admin_path %> </h2>
<%= will_paginate %>
  <ul class="admins">
    <%= render @admins %>
  </ul>
<%= will_paginate %>

app/views/admin/admins/new.html.erb
<% provide(:title, "Create new admin") %>
<h1> Create new admin </h1>
<div class="row">
  <div class="span6 offset3">
    <%= form_for [:admin, @admin] do |f| %>
      <%= render 'shared/error_messages' %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation %>

      <br/>
      <%= f.submit "Create", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/admin/admins/show.html.erb
<% provide(:title, "View Admin") %>
<h1><%= @admin.name %></h1>
<h2><%= @admin.email %></h2>